dependencies {
    implementation(project(":modules:CTNH-Bio"))
    jarJar(project(":modules:CTNH-Bio")){ transitive = false }
    implementation(project(":modules:CTPP"))
    jarJar(project(":modules:CTPP")){ transitive = false }
    modImplementation(project(":modules:CTNH-Lib")){ transitive = false }
    jarJar(project(":modules:CTNH-Lib")){ transitive = false }
    implementation(project(":modules:CTNH-Energy"))
    jarJar(project(":modules:CTNH-Energy")){ transitive = false }
    implementation(project(":modules:CTNH-Mana"))
    jarJar(project(":modules:CTNH-Mana")){ transitive = false }
    implementation(project(":modules:CTNH-Astral"))
    jarJar(project(":modules:CTNH-Astral")){ transitive = false }
    jarJar(project(":modules:GregTech-Modern")){ transitive = false }

    //modImplementation("extra-mods:create_connected-26.1-all")
    jarJar("extra-mods:scg-ctnh:1.1.1")
    jarJar("extra-mods:kallfix_sub-1.0:1.0")

    runtimeOnly(ctnh.graphlib)

    // AE2
    modImplementation(ctnh.ae2)
    modImplementation(ctnh.guideme)
    modImplementation(ctnh.ae2cs)
    modImplementation(ctnh.glodium)
    modImplementation(ctnh.eae)
    modImplementation(ctnh.omnicells)

    // Create addons
    modImplementation(ctnh.createmetallurgy)
    modImplementation(ctnh.createvintage)
    modImplementation(ctnh.createliquidfuel)
//    modImplementation(ctnh.createoreexcavation)
    modImplementation(ctnh.creatediesel)
    modImplementation(ctnh.immersiveaircraft)
    modImplementation(ctnh.createnewage)

    // season
    modImplementation(ctnh.glitchcore)
    modImplementation(ctnh.ecliptic)

    // Curios
    modCompileOnly(variantOf(forge.curios) { classifier("api") })

    // ars
    modImplementation(ctnh.geckolib)
    modImplementation(ctnh.arsnouveau)

    // ad
    modImplementation(ctnh.resourcefullib)
    modImplementation(ctnh.resourcefulconfig)
    modImplementation(ctnh.botarium)
    modImplementation(ctnh.adastra)

    modImplementation(ctnh.aeroblender)
    modImplementation(ctnh.terrablender)
    modImplementation(ctnh.aether)
    modImplementation(ctnh.deepaether)

    modImplementation(ctnh.architecturyapi)
    modImplementation(ctnh.ftblibrary)
    modImplementation(ctnh.ftbultimine)
    modImplementation(ctnh.ftbteams)
    modImplementation(ctnh.ftbchunks)

    modImplementation(ctnh.patchouli)
    modImplementation(ctnh.botania)

    // EnderIO
    modCompileOnly(variantOf(ctnh.eio) { classifier("api") })
    modImplementation(ctnh.eio)

    modImplementation(ctnh.legendary)

    // Blood Magic
    modImplementation(ctnh.bloodmagic)
    modImplementation(ctnh.extrabotany)
    modImplementation(ctnh.mythicbotany)
    annotationProcessor(ctnh.libx)
    modImplementation(ctnh.libx)

    // Apotheosis
    modImplementation(ctnh.apotheosis)
    modImplementation(ctnh.attributelib)
    modImplementation(ctnh.placebo)

    // Twilight forest
    modImplementation(ctnh.twilightforest)

    // Hostile Neural NetWork
    modImplementation(ctnh.hostile)

    // Biomancy
    modImplementation(ctnh.biomancy)
    modImplementation(ctnh.biofactory)

    // Re-Avaritia
    modImplementation(ctnh.avaritia)

    // tconstruct
    modImplementation(ctnh.tconstruct)
    modImplementation(ctnh.mantle)

    modImplementation(ctnh.javd)
    modImplementation(ctnh.trenzalore)
    modImplementation(ctnh.sophisticatedcore)
    modImplementation(ctnh.sophisticatedbackpacks)
    modImplementation(ctnh.alexscaves)
    modImplementation(ctnh.citadel)

    modLocalRuntime(ctnh.curios)
    modLocalRuntime(ctnh.constructionwand)

    // Jack's Economy
    modImplementation(ctnh.jackseconomy)
    modLocalRuntime(ctnh.curios)
    modLocalRuntime(ctnh.constructionwand)

    modImplementation(ctnh.lendercataclysm)

    modImplementation(ctnh.angelblock)
}
