dependencies {
    compileOnly("org.jetbrains:annotations:26.0.1")

    // Mixin
    annotationProcessor('org.spongepowered:mixin:0.8.5:processor')
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0-rc.3"))

    implementation(project(":modules:CTNH-Bio"))
    jarJar(project(":modules:CTNH-Bio")){transitive = false}
    implementation(project(":modules:CTPP"))
    jarJar(project(":modules:CTPP")){transitive = false}
    modImplementation(project(":modules:CTNH-Lib")){transitive = false}
    jarJar(project(":modules:CTNH-Lib")){transitive = false}
    implementation(project(":modules:CTNH-Energy"))
    jarJar(project(":modules:CTNH-Energy")){transitive = false}
    implementation(project(":modules:CTNH-Mana"))
    jarJar(project(":modules:CTNH-Mana")){transitive = false}

    jarJar(modImplementation("extra-mods:gtceu-1.20.1:7.4.1-ctnh-slim")){transitive = false}

    // JEI, EMI, Jade
    //modCompileOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
    //modCompileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    //modRuntimeOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
    //modCompileOnly("dev.emi:emi-forge:${emi_version}+${minecraft_version}")
    //modRuntimeOnly("dev.emi:emi-forge:${emi_version}+${minecraft_version}")
    modImplementation("curse.maven:jade-324717:6855440")

    // GregTech and dependencies
    //modImplementation("com.gregtechceu.gtceu:gtceu-${minecraft_version}:${gtceu_version}:slim") { transitive = false }
    modImplementation("com.lowdragmc.ldlib:ldlib-forge-${minecraft_version}:${ldlib_version}") { transitive = false }
    modImplementation("com.tterrag.registrate:Registrate:${registrate_version}")
    modImplementation("dev.toma.configuration:configuration-forge-${minecraft_version}:${configuration_version}")

    //Create
    modImplementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    modImplementation("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")
    modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")


    // Create addons
    modImplementation("curse.maven:createmetallurgy-1007404:6741785")
    modImplementation("curse.maven:createvintage-1255448:6635459")
    modImplementation("curse.maven:create-liquid-fuel-840734:5217310")
    //modImplementation("com.hlysine.create_connected:create_connected:26.1")
    modImplementation("extra-mods:create_connected-26.1-all")
    modImplementation("curse.maven:create-ore-excavation-649832:6633054")

    //season
    modImplementation("curse.maven:glitchcore-955399:5787839")
    modImplementation("curse.maven:ecliptic_season-1118306:6752783")

    // Curios
    modRuntimeOnly("top.theillusivec4.curios:curios-forge:${curios_version}")
    modCompileOnly("top.theillusivec4.curios:curios-forge:${curios_version}:api")

    //ars
    modImplementation("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
    //modImplementation("com.hollingsworth.ars_nouveau:ars_nouveau-${minecraft_version}:${arsnouveau_version}")

    //ad
    modImplementation("com.teamresourceful.resourcefullib:resourcefullib-forge-${minecraft_version}:${resourcefullib_version}")
    modImplementation("com.teamresourceful.resourcefulconfig:resourcefulconfig-forge-${minecraft_version}:${resourcefulconfig_version}")
    modImplementation("earth.terrarium.botarium:botarium-forge-${minecraft_version}:${botarium_version}")
    modImplementation("earth.terrarium.adastra:ad_astra-forge-${minecraft_version}:${ad_astra_version}")

    modImplementation("curse.maven:aeroblender-879879:4789008")
    modImplementation("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
    modImplementation("curse.maven:terrablender-563928:5378180")
    modImplementation("curse.maven:aether-255308:5302178")
    modImplementation("curse.maven:deep-aether-852465:5441091")

    modImplementation("curse.maven:architectury-api-419699:5137938")
    modImplementation("curse.maven:ftb-library-forge-404465:5567591")
    modImplementation("curse.maven:ftb-ultimine-forge-386134:5363345")

    modImplementation("curse.maven:patchouli-306770:4966125")
    //modImplementation("vazkii.botania:Botania:${botania_version}")

    modRuntimeOnly("curse.maven:modernfix-790626:6719008")

    // KubeJS
    modImplementation("dev.latvian.mods:kubejs-forge:${kubejs_version}")
    modImplementation("dev.latvian.mods:rhino-forge:${rhino_version}")
    modImplementation("dev.architectury:architectury-forge:${architectury_version}")

    // EnderIO
    modCompileOnly("com.enderio:EnderIO:${enderio_version}:api")
    modImplementation("com.enderio:EnderIO:${enderio_version}")

    runtimeOnly "dev.gigaherz.graph:GraphLib3:$graphlib_version"

    modImplementation("appeng:appliedenergistics2-forge:${ae2_version}")
    modImplementation("curse.maven:guideme-1173950:6679102")
    modImplementation("curse.maven:legendary_survival_overhaul-840254:6750561")



    // Blood Magic
    //modImplementation("maven.modrinth:blood-magic:${bloodmagic_version}")

    //modImplementation("curse.maven:gtmthings-1104310:6764930")

    //modImplementation("curse.maven:mythicbotany-400058:5101899")
    annotationProcessor "org.moddingx:LibX:${minecraft_version}-${libx_version}"
    modImplementation("org.moddingx:LibX:${minecraft_version}-${libx_version}")

    // Apotheosis
    modImplementation("curse.maven:apotheosis-313970:6461960")
    modImplementation("curse.maven:attributelib-898963:5634071")
    modImplementation("curse.maven:placebo-283644:6274231")


    // Twilight forest
    modImplementation("curse.maven:twilight_forest-227639:5468648")

    //Hostile Neural NetWork
    modImplementation("curse.maven:hostile_neural_network-552574:5895036")

    // Biomancy
    modImplementation("curse.maven:biomancy-492939:5886758")
    modImplementation("curse.maven:bio-factory-1136762:6293100")

    modRuntimeOnly("curse.maven:constructionwand-399558:4684054")
    //modRuntimeOnly("curse.maven:just-enough-characters-250702:6680042")
    //modRuntimeOnly("curse.maven:not-enough-crashes-forge-442354:6598273")
    // lombok
    //compileOnly 'org.projectlombok:lombok:1.18.24'
    //annotationProcessor 'org.projectlombok:lombok:1.18.24'

    //Re-Avaritia
    modImplementation("committee.nova.mods:avaritia-forge:${avaritia_version}")

    //modRuntimeOnly("curse.maven:xaeros-minimap-263420:6778028")
    //modRuntimeOnly("curse.maven:xaeros-world-map-317780:6778091")
    modImplementation("curse.maven:sophisticated-core-618298:6596375")

    modImplementation("curse.maven:javd-370890:4803995")
    modImplementation("curse.maven:trenzalore-870210:4848244")
    //modImplementation("maven.modrinth:pneumaticcraft-repressurized:${pneumaticcraft_version}")
    //modImplementation("curse.maven:compressedcreativity-549381:6603441")
    //modImplementation("curse.maven:appliedpneumatics-1355087:7124464")
    modImplementation("curse.maven:omni-cells-1359517:7152251")
}