package io.github.cpearl0.ctnhcore.common.item;
import tech.vixhentx.mcmod.ctnhlib.langprovider.Lang;
import com.ctnhlang.CN;
import com.ctnhlang.EN;
import com.ctnhlang.Key;

import com.gregtechceu.gtceu.api.item.ComponentItem;

import net.minecraft.network.chat.Component;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.level.Level;

import lombok.Getter;
import org.jetbrains.annotations.Nullable;

import java.util.List;
import java.util.function.Supplier;

public class IDroneItem extends ComponentItem {

    @Key("ctnh.item.drone_durability")
    @CN("无人机最大耐久:%d")
    @EN("Maximum Drone Durability: %d")
    public static Lang itemDroneDurability;


    @Key("ctnh.item.drone_eut")
    @CN("单个无人机产生的电压: %dEU/t")
    @EN("Voltage generated by one drone: %d EU/t")
    public static Lang itemDroneEut;


    @Key("ctnh.item.drone_tier")
    @CN("无人机等级：%d")
    @EN("Drone Tier: %d")
    public static Lang itemDroneTier;



    @Getter
    public int tier;
    @Getter
    public int eut;
    @Getter
    public int durability;

    public IDroneItem(Properties properties, int tier, int eut, int durability, Supplier<Item> finishedItem) {
        super(properties
                .durability(durability)
                .rarity(Rarity.EPIC));
        this.tier = tier;
        this.eut = eut;
        this.durability = durability;
    }

    @Override
    public void appendHoverText(ItemStack stack, @Nullable Level level, List<Component> tooltipComponents,
                                TooltipFlag isAdvanced) {
        tooltipComponents.add(itemDroneTier.translate( String.format("%d", tier)));
        tooltipComponents.add(itemDroneEut.translate( String.format("%d", eut)));
        tooltipComponents.add(itemDroneDurability.translate( String.format("%d", durability)));
        super.appendHoverText(stack, level, tooltipComponents, isAdvanced); // 调用父类方法以处理原版提示信息
    }
}
